### ISSUE TITLE
good start but why IIS for angular client?

### ISSUE THREAD

**Issue by mellogrand** [GeertHuls/SecuredApi#2]
interesting solution. difficult to set up and try because of IIS dependencies. 
would be nice to have is on IIsexpress localhost and angular client with gulp on node-express

thanks anyway
sergio

**Comment by GeertHuls** [comment]
Yeah, I can imagine it might take a few attempts to get it up and running the first time...
But you can configure each project to use iis express instead. If you do so, make sure you adjust the app settings accordingly throughout the project. Also make sure the identity server get https because oauth2 requires ssl.

Currently only the WsFederationServer is configured with iis express so basically it's the same thing for the others as well.

Sure you can choose whatever webstack for the client app you want, it's all good. I've used .net and iis because it very similar to the other project in terms of the ecosystem. Also keep in mind that is just a proof of concept, that it doesn't have to be perfect. For instance it doesn't even have bundling and minification.

Cheers.
